# Generated by Django 5.2.6 on 2025-09-10 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='categoria',
            field=models.CharField(choices=[('NEBULOSA', 'Nebulosa'), ('ESTRELA', 'Estrela'), ('GALÁXIA', 'Galáxia'), ('PLANETA', 'Planeta')], default='', max_length=50),
        ),
        migrations.AddField(
            model_name='imagem',
            name='legenda',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
