# Generated by Django 5.2.6 on 2025-09-10 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0002_imagem_categoria_imagem_legenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='publicada',
            field=models.BooleanField(default=True),
        ),
    ]
