# Generated by Django 5.2.6 on 2025-09-10 12:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_imagem_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagem',
            name='data_imagem',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
