# Generated by Django 5.2.6 on 2025-09-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_imagem_data_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagem',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
